"""initial schema

Revision ID: 963291c89037
Revises: 
Create Date: 2026-07-03 20:53:57.870685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963291c89037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Attractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Attractions_category'), ['category'], unique=False)

    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_firebase_uid'), ['firebase_uid'], unique=True)

    op.create_table('ChatLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ChatLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ChatLogs_user_id'), ['user_id'], unique=False)

    op.create_table('Feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['Attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Feedback_attraction_id'), ['attraction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Feedback_user_id'), ['user_id'], unique=False)

    op.create_table('Interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.Enum('view', 'like', 'visit', name='interactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['Attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Interactions_attraction_id'), ['attraction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Interactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_interactions_user_attraction', ['user_id', 'attraction_id'], unique=False)

    op.create_table('Itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Itineraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Itineraries_user_id'), ['user_id'], unique=False)

    op.create_table('UploadedImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('recognition_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('UploadedImages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_UploadedImages_user_id'), ['user_id'], unique=False)

    op.create_table('ItineraryItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['Attractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['Itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ItineraryItems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ItineraryItems_attraction_id'), ['attraction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ItineraryItems_itinerary_id'), ['itinerary_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItineraryItems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ItineraryItems_itinerary_id'))
        batch_op.drop_index(batch_op.f('ix_ItineraryItems_attraction_id'))

    op.drop_table('ItineraryItems')
    with op.batch_alter_table('UploadedImages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_UploadedImages_user_id'))

    op.drop_table('UploadedImages')
    with op.batch_alter_table('Itineraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Itineraries_user_id'))

    op.drop_table('Itineraries')
    with op.batch_alter_table('Interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_interactions_user_attraction')
        batch_op.drop_index(batch_op.f('ix_Interactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_Interactions_attraction_id'))

    op.drop_table('Interactions')
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_Feedback_attraction_id'))

    op.drop_table('Feedback')
    with op.batch_alter_table('ChatLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ChatLogs_user_id'))

    op.drop_table('ChatLogs')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    with op.batch_alter_table('Attractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Attractions_category'))

    op.drop_table('Attractions')
    # ### end Alembic commands ###
